// react-my-notes/src/App.jsx
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Outlet } from "react-router-dom";

function App() {
  return (
    <>
      {/* Navbar  */}
      <Navbar />

      {/* Main content start */}
      <main class="min-h-[85vh]">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4 mt-8">
          <Outlet />
        </div>
      </main>
      {/* Main content ends */}

      {/* Footer */}
      <Footer />
    </>
  );
}

export default App;

// vue-my-notes/src/App.vue
<script setup lang="ts">
import { RouterView } from "vue-router";
import Navbar from "@/components/Navbar.vue";
import Footer from "@/components/Footer.vue";
</script>

<template>
  <Navbar />
  <main class="min-h-[80vh]">
    <div
      class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4 mt-16"
    >
      <RouterView />
    </div>
  </main>

  <Footer />
</template>
