// react-my-notes/src/components/Footer.jsx
import { Link } from "react-router-dom";

const Footer = () => {
  const year = new Date().getFullYear();
  return (
    <footer className="bg-white shadow">
      <hr className="border-gray-200 sm:mx-auto" />
      <div className="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <span className="block text-sm text-gray-500 sm:text-center">
          © {year}
          <Link to="/" className="hover:underline">
            My Notes
          </Link>
          . All Rights Reserved.
        </span>
      </div>
    </footer>
  );
};

export default Footer;

// vue-my-notes/src/components/Footer.vue
<script setup>
const year = new Date().getFullYear();
</script>

<template>
  <footer class="bg-white shadow">
    <hr class="border-gray-200 sm:mx-auto" />
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
      <span class="block text-sm text-gray-500 sm:text-center"
        >© {{ year }}
        <RouterLink to="/" class="hover:underline">My Notes</RouterLink>. All
        Rights Reserved.</span
      >
    </div>
  </footer>
</template>
