// react-my-notes/src/components/Navbar.jsx
import { Link } from "react-router-dom";

const Navbar = () => {
  return (
    <nav className="bg-white border-gray-200 fixed w-full z-20 top-0 start-0 border-b">
      <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <Link
          to="/"
          className="flex items-center space-x-3 rtl:space-x-reverse"
        >
          <span className="self-center text-2xl font-semibold whitespace-nowrap">
            My Notes
          </span>
        </Link>

        <div className="flex md:order-2 space-x-3 md:space-x-2 rtl:space-x-reverse">
          <Link to="/login">
            <button
              type="button"
              className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"
            >
              Login
            </button>
          </Link>

          <Link to="/register">
            <button
              type="button"
              className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"
            >
              Register
            </button>
          </Link>

          <button
            type="button"
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center hidden"
          >
            Logout
          </button>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// vue-my-notes/src/components/Navbar.vue
<script setup lang="ts"></script>

<template>
  <nav
    class="bg-white border-gray-200 fixed w-full z-20 top-0 start-0 border-b"
  >
    <div
      class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
    >
      <RouterLink
        to="/"
        class="flex items-center space-x-3 rtl:space-x-reverse"
      >
        <span class="self-center text-2xl font-semibold whitespace-nowrap"
          >My Notes</span
        >
      </RouterLink>

      <div class="flex md:order-2 space-x-3 md:space-x-2 rtl:space-x-reverse">
        <RouterLink to="/login">
          <button
            type="button"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"
          >
            Login
          </button>
        </RouterLink>

        <RouterLink to="/register">
          <button
            type="button"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"
          >
            Register
          </button>
        </RouterLink>

        <button
          type="button"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center hidden"
        >
          Logout
        </button>
      </div>
    </div>
  </nav>
</template>
